services:
  - type: web
    name: sarah-surrogate-node
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /status
    envVars:
      - key: CIRCLE_API_KEY
        sync: false
      - key: SARAH_USDC_WALLET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
